services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: php-basic-web
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    networks: [appnet]

  mysql:
    image: mysql:8.4
    container_name: php-basic-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: videojocs_mvc
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [appnet]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: php-basic-pma
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks: [appnet]

  # OPCIONAL: VS Code al navegador (code-server)
  code:
    image: lscr.io/linuxserver/code-server:latest
    container_name: php-basic-code
    environment:
      PASSWORD: "alumnat"        # canvia-ho si vols
      # SENSE PERSISTIR CREDENCIALS EN EQUIPS COMPARTITS
    ports:
      - "8081:8443"
    volumes:
      - ./app:/config/workspace
    networks: [appnet]
    # Treu aquest servei si no el vols

volumes:
  mysql-data:

networks:
  appnet:
    driver: bridge
